### ISSUE TITLE
Final Zip Not Downloaded Exception

### ISSUE THREAD

**Issue by laurent-laporte-pro** [AntaresSimulatorTeam/antares-launcher#42]
An exception is raised when the user tries to launch a study.

Failed to launch study 7c7cefb7-d552-436f-9887-b69f4e531dd8: see stack trace below:

```python
Traceback (most recent call last):
  File "/antarest/launcher/adapters/slurm_launcher/slurm_launcher.py", line 540, in _run_study
    self._call_launcher(launcher_args, self.launcher_params)
  File "/antarest/launcher/adapters/slurm_launcher/slurm_launcher.py", line 585, in _call_launcher
    run_with(arguments, parameters, show_banner=False)
  File "/usr/local/lib/python3.8/site-packages/antareslauncher/main.py", line 178, in run_with
    launcher.run()
  File "/usr/local/lib/python3.8/site-packages/antareslauncher/antares_launcher.py", line 66, in run
    self.run_once_mode()
  File "/usr/local/lib/python3.8/site-packages/antareslauncher/antares_launcher.py", line 45, in run_once_mode
    self.retrieve_controller.retrieve_all_studies()
  File "/usr/local/lib/python3.8/site-packages/antareslauncher/use_cases/retrieve/retrieve_controller.py", line 80, in retrieve_all_studies
    self.study_retriever.retrieve(study)
  File "/usr/local/lib/python3.8/site-packages/antareslauncher/use_cases/retrieve/study_retriever.py", line 64, in retrieve
    self._download_final_zip()
  File "/usr/local/lib/python3.8/site-packages/antareslauncher/use_cases/retrieve/study_retriever.py", line 43, in _download_final_zip
    self._current_study = self.final_zip_downloader.download(self._current_study)
  File "/usr/local/lib/python3.8/site-packages/antareslauncher/use_cases/retrieve/download_final_zip.py", line 43, in download
    self._do_download()
  File "/usr/local/lib/python3.8/site-packages/antareslauncher/use_cases/retrieve/download_final_zip.py", line 84, in _do_download
    raise FinalZipNotDownloadedException(
antareslauncher.use_cases.retrieve.download_final_zip.FinalZipNotDownloadedException
```

**Comment by laurent-laporte-pro** [comment]
We may have an issue with the way with parse the output of the `sacct` command on the SLURM server.

Currently, Antares Launcher use the following command:

```sh
sacct -j 7158705 -n --format=state | head -1 | awk -F" " '{print $1}'
```

The `head -1` command keeps the first line of the output. But, the first line may correspond to a job step which is not the main step.

Here is a way to get the list of step states using a CSV-like format:

```sh
sacct -j 7016271 --format=JobID,JobName,State -P
JobID|JobName|State
7016271|d4fb3568-2245-4979-88b7-8508e08601ba|COMPLETED
7016271.batch|batch|COMPLETED
7016271.0|unzip|COMPLETED
7016271.1|antares-solver|COMPLETED
7016271.2|zip|COMPLETED
7016271.3|rm|COMPLETED
```

**Comment by laurent-laporte-pro** [comment]
Using the `-j {JobID}` option with the `sacct` command can give approximate results when an exact match on the `JobID` is not found in the job list. In this case, the command seems to return the list of jobs whose ID is closest to the search ID. In production, we are in the case where the jobs are not purged and therefore, the command "recycles" old IDs.
